language: python

sudo: false

branches:
  only:
    - master

python:
  - "2.7"

virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
    - python-numpy
    - python-scipy

install:
 - pip install -r requirements.txt
 - pip install coveralls

script:
 - nosetests --with-coverage SBB

after_success:
 - coveralls

cache:
 - apt
 - pip