language: python

sudo: false

branches:
  only:
    - master

python:
  - "2.7"

addons:
  apt:
    packages:
    - libatlas3gf-base
    - python-numpy
    - python-scipy

install:
 - pip install -r requirements.txt

script:
 - nosetests

cache:
 - apt
 - pip